In [2]:
My_String =" sdfghjkhgfhjkjh"
My_String 
#To reverse the String 
print(My_String[::-1])
#The Third Parameter In the Slicing is Using To jump 
My_String[2:7:2]
 

hjkjhfghkjhgfds 


'dgj'

In [3]:
#Strings are immutable
My_String="Chaimaa"
x="Just be patient "+ My_String +" All things will be Ok "
x

'Just be patient Chaimaa All things will be Ok '

In [4]:
x.upper()

'JUST BE PATIENT CHAIMAA ALL THINGS WILL BE OK '

In [5]:
x.split()

['Just', 'be', 'patient', 'Chaimaa', 'All', 'things', 'will', 'be', 'Ok']

In [6]:
x.split('i')

['Just be pat', 'ent Cha', 'maa All th', 'ngs w', 'll be Ok ']

In [7]:
#Print Formatting With String 
print('This is String {}'.format('Inserted'))

This is String Inserted


In [8]:
print(' the {} {} {}'.format('fox','brown','quik'))

 the fox brown quik


In [9]:
print(' the {0} {0} {0}'.format('fox','brown','quik'))

 the fox fox fox


In [10]:
print(' the {q} {q} {q}'.format(f='fox',b='brown',q='quik'))

 the quik quik quik


In [11]:
#Float Formatting With print 
result =2112/7
result 
print('The result Is {}'.format(result))

The result Is 301.7142857142857


In [12]:
print('The resulr Is {r}'.format(r=result))

The resulr Is 301.7142857142857


In [13]:
print('The result Is {r:1.4f}'.format(r=result))
# (1.4)Mean that we should take four number after the Comma.

The result Is 301.7143


In [14]:
#print('The resulr Is {r:x.yf}'.format(r=result))
#x is for Making Space Between  String and Float Number 
#y is to precise the Number of decimal after the Comma 

In [15]:
#f-Strings
name ="Chaimaa El Kasbaji"
print (f'The Complete Name Of this Student is {name}')
 

The Complete Name Of this Student is Chaimaa El Kasbaji


In [16]:
name_="Chaimaa"
age=21
print(f'{name_} is {age} years Old')

Chaimaa is 21 years Old


In [17]:
#Lists in Python 
#Lists Can have diffrent Object Type 
#Lists Are Immutuble

In [18]:
my_list=['One',1234,1234.4254]
len(my_list)

3

In [19]:
my_list[1:]

[1234, 1234.4254]

In [20]:
another_list=['Four','Five']
theResult_list=my_list+another_list
theResult_list

['One', 1234, 1234.4254, 'Four', 'Five']

In [21]:
theResult_list[1]="two"
theResult_list

['One', 'two', 1234.4254, 'Four', 'Five']

In [22]:
 theResult_list

['One', 'two', 1234.4254, 'Four', 'Five']

In [23]:
theResult_list[2]="Three"

In [24]:
#append is to add element in the last of the list 
theResult_list.append('Six')
theResult_list




['One', 'two', 'Three', 'Four', 'Five', 'Six']

In [25]:
#pop remove element from the Last Of The List And return The pomped Item 
theResult_list.pop()
theResult_list


['One', 'two', 'Three', 'Four', 'Five']

In [26]:
theResult_list.pop()

'Five'

In [27]:
pompedItem =theResult_list.pop()

In [28]:
pompedItem

'Four'

In [29]:
theResult_list.pop(1)
theResult_list

['One', 'Three']

In [30]:
new_list=[1,2,3,4,5,6,7]
new_list.reverse()
new_list

[7, 6, 5, 4, 3, 2, 1]

In [31]:
list=['a','b','c','u']
list.sort()

In [32]:
list

['a', 'b', 'c', 'u']

In [33]:
#The bool() function converts the given value to a boolean value ( True or False )
print(bool( 5<4))

False


In [41]:
Username=input(" What's is your UserName ")
Password =input(" What's is your Password ")
print(f'{Username} ,your password is {Password} ,{len(Password)} letters long')

 What's is your UserName DXCGFV
 What's is your Password HJGDFCGVHJ
DXCGFV ,your password is HJGDFCGVHJ ,10 letters long


In [42]:
#When We Copy A List In other all changes Applied On the Second List Will applied to the First List
amazon_cart=['notebooks','sungLasses','toys','grapes']
amazon_cart[0]='laptop'
new_cart=amazon_cart
#That mean that the Two Lists are  identical
#new_cart=amazon_cart[:](But In this Case that mean that we create a new Copy of the list That mean that Every Change in the Second List will Not affect The First List)

new_cart[0]='gum'
print(new_cart)
print(amazon_cart)

['gum', 'sungLasses', 'toys', 'grapes']
['gum', 'sungLasses', 'toys', 'grapes']


In [43]:
my_dict ={'key1':'value1','key2':'value2'}
my_dict ['key1']
prices_loockup={'Apple':15,'Oranger':23,'Milk':5.80}

In [44]:
prices_loockup['Apple']

15

In [45]:
d={'k1':123,'k2':[0,1,2],'k3':{'insideKey':100}}

In [46]:
d['k2']

[0, 1, 2]

In [47]:
d['k3']

{'insideKey': 100}

In [48]:
d['k3']['insideKey']

100

In [49]:
d={'key1':['a','b','c']}

In [50]:
d

{'key1': ['a', 'b', 'c']}

In [51]:
d['key1'][2].upper()

'C'

In [52]:
Novel_List=d['key1']
Novel_List


['a', 'b', 'c']

In [53]:
Letter=Novel_List[2]
Letter

'c'

In [54]:
Letter.upper()

'C'

In [55]:
#Add a Key To a Dictionnary
d={'key1': 'value_1','key2':'value_2'}
d['key3']='value_3'
d

{'key1': 'value_1', 'key2': 'value_2', 'key3': 'value_3'}

In [56]:
#d['key']='value' Is To overrid an Exist Value In the Dictionnary 

In [57]:
d.keys()

dict_keys(['key1', 'key2', 'key3'])

In [58]:
d.values()

dict_values(['value_1', 'value_2', 'value_3'])

In [59]:
d.items()

dict_items([('key1', 'value_1'), ('key2', 'value_2'), ('key3', 'value_3')])

In [60]:
#Tuples
#Tuples are immutable
t=(1,2,3)
Lis=[1,2,3]
type(t)
 

tuple

In [61]:
type(Lis)
 

list

In [62]:
len(t)
 

3

In [63]:
t=('One',2)
t[0]


'One'

In [64]:
t[-1]

2

In [65]:
t=('a','a','b')

In [66]:
t.count('a')

2

In [67]:
t.index('a')

0

In [68]:
t.index('b')

2

In [69]:
t

('a', 'a', 'b')

In [70]:
Lis[0]='New'

In [71]:
Lis

['New', 2, 3]

In [72]:
#t[0]='New'
#Generate A error because Tuples Are immutable.

In [73]:
type(False)

bool

In [74]:
1==1

True

In [75]:
#To Assign A Null value ,
b=None
#Files
#Create A text File
 


In [76]:
%%writefile myfile.txt
Hello this is a text file
this is the Second line
this is third line

Overwriting myfile.txt


In [77]:
myfile=open('myfile.txt')

In [78]:
myfile

<_io.TextIOWrapper name='myfile.txt' mode='r' encoding='cp65001'>

In [79]:
#pwd is used to know the LOCATION oF your Notbook

In [80]:
pwd

'C:\\Users\\elkas'

In [81]:
#To read your TextFile
myfile.read()
 

'Hello this is a text file\nthis is the Second line\nthis is third line\n'

In [82]:
#reading again textFile
myfile.read()
 

''

In [83]:
#To read again the TextFile we should return the Cursor to Zero we Use seek function
myfile.seek(0)
#To return ' to zero 

0

In [84]:
#This Function Read Each Line
myfile.readlines()

['Hello this is a text file\n',
 'this is the Second line\n',
 'this is third line\n']

In [85]:
myfile.close()

In [86]:
#this bloock Is To avoid any Confusion using Our TextFile with Storing it in Variable that we use in the Complete Code
with open('myfile.txt') as my_new_file:
    contents=my_new_file.read()

In [87]:
contents

'Hello this is a text file\nthis is the Second line\nthis is third line\n'

In [88]:
%%writefile my_new_file.txt
The First Line
The Second Line 
The Third Line

Overwriting my_new_file.txt


In [89]:
with open('my_new_file.txt',mode='r') as f:
    print(f.read())

The First Line
The Second Line 
The Third Line



In [90]:

with open ('my_new_file.txt',mode='a') as f:
    f.write('Four On Fourth')
   

In [91]:
with open('my_new_file.txt',mode='r') as f:
    print(f.read())

The First Line
The Second Line 
The Third Line
Four On Fourth


In [92]:
#r mode is to read the FileText
#a mode is to append a part to the FileText
#w mode is to write In a textFile Or Create it if it doesn't exist.
with open ('TextFile.text',mode='w') as f:
    print(f.write('The TextFile Is Created Now'))

27


In [93]:
with open ('TextFile.text',mode='r') as f:
    print(f.read())

The TextFile Is Created Now


In [94]:
#Difference Between sort() and Sorted() Functions
List_=[1,6,9,0]
List_.sort()
List_
# When we sort() Function we need to Call the List in order see the Sorted List in inverse sorted() function return automatically the sorted List.
sorted(List_)

[0, 1, 6, 9]

In [95]:
#How to insert an element In specific position in a List /The Syntax is
#list_name.insert(position, 'element')

In [96]:
#ControlFlow
#Example
hungry =True
if hungry:
    print('This is True')

This is True


In [97]:
#loops
List=[1,2,5,8,9,9,0]

In [98]:
for i in List:
    print('number')

number
number
number
number
number
number
number


In [99]:
List_Sum =0
for j in  List:
    List_Sum=List_Sum+j
    print(List_Sum)
    #To get Just THE last Summee
    #the print function of the bloock of the Loop function like the Code below
    

1
3
8
16
25
34
34


In [100]:
List_Sum =0
for j in  List:
    List_Sum=List_Sum+j
print(List_Sum)

34


In [101]:
for j in 'Hello world':
    print(j)

H
e
l
l
o
 
w
o
r
l
d


In [102]:
for j in 'Hello world':
    print('Chaimaa')

Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa
Chaimaa


In [103]:
for _ in 'Hello world':
    print('El Kasbaji')

El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji
El Kasbaji


In [104]:
tup=(1,2,3)
for item in tup:
    print(item)
    

1
2
3


In [105]:
#Tuples Combined To a list In this Examlpe offers the opportunity to run two intervals simultaneously.
ListOfTup=[(1,2),(3,4),(5,6),(7,8)]
len(ListOfTup )

4

In [106]:
for item in ListOfTup:
    print(item)

(1, 2)
(3, 4)
(5, 6)
(7, 8)


In [107]:
for (a,b)in ListOfTup:
    print(a)
    print(b)

1
2
3
4
5
6
7
8


In [108]:
#We Can also  run n intervals simultaneously


In [109]:
#Loops and Dictionnary
d={'key1':'Chaimaa','key2':'El kasbaji'}
for item in d:
    print(item)

key1
key2


In [110]:
for item in d.items():
    print(item)

('key1', 'Chaimaa')
('key2', 'El kasbaji')


In [111]:
for key,value in d.items():
    print(value)

Chaimaa
El kasbaji


In [112]:
for value in d.values():
    print(value)

Chaimaa
El kasbaji


In [113]:
print("Chaimaa") 

Chaimaa


In [114]:
#while loop
x=0
while x<7:
    pass
    print(f'the value of x is {x}')
    x=x+1

the value of x is 0
the value of x is 1
the value of x is 2
the value of x is 3
the value of x is 4
the value of x is 5
the value of x is 6


In [115]:
myString="Summy"
for i in myString:
    pass
print('pass Doas nothing that All is just to respect the syntax of the loop')

pass Doas nothing that All is just to respect the syntax of the loop


In [116]:
myString="Summy"
for i in myString:
    if i=='S':
        continue
    print(i)
print('continue is to jump the result of execution of the Condition ')
 

u
m
m
y
continue is to jump the result of execution of the Condition 


In [117]:
myString="Summy"
for i in myString:
    if i=='y':
        break
    print(i)
print(' break is to go out from the loop ')

S
u
m
m
 break is to go out from the loop 


In [118]:
 for i in range (0,10):
        print(i)

0
1
2
3
4
5
6
7
8
9


In [119]:
list(range(0,10,2))

TypeError: 'list' object is not callable

In [120]:
index_count=0
for letter in 'Chaimaa El kasbaji':
    print('the letter is {} and his index is {} '.format(letter,index_count))
    index_count+=1

the letter is C and his index is 0 
the letter is h and his index is 1 
the letter is a and his index is 2 
the letter is i and his index is 3 
the letter is m and his index is 4 
the letter is a and his index is 5 
the letter is a and his index is 6 
the letter is   and his index is 7 
the letter is E and his index is 8 
the letter is l and his index is 9 
the letter is   and his index is 10 
the letter is k and his index is 11 
the letter is a and his index is 12 
the letter is s and his index is 13 
the letter is b and his index is 14 
the letter is a and his index is 15 
the letter is j and his index is 16 
the letter is i and his index is 17 


In [121]:
index_count=0
word='Chaimaa El kasbaji'
for letter in  word:
    print( word[index_count])
    index_count+=1

C
h
a
i
m
a
a
 
E
l
 
k
a
s
b
a
j
i


In [122]:
word='Chaimaa El kasbaji'

In [123]:
for item in enumerate(word):
    print(item)

(0, 'C')
(1, 'h')
(2, 'a')
(3, 'i')
(4, 'm')
(5, 'a')
(6, 'a')
(7, ' ')
(8, 'E')
(9, 'l')
(10, ' ')
(11, 'k')
(12, 'a')
(13, 's')
(14, 'b')
(15, 'a')
(16, 'j')
(17, 'i')


In [124]:
for index,letter in enumerate(word):
    print(index)
    print(letter)
    print('\n')
    

0
C


1
h


2
a


3
i


4
m


5
a


6
a


7
 


8
E


9
l


10
 


11
k


12
a


13
s


14
b


15
a


16
j


17
i




In [125]:
list1=[1,2,3]
list2=['a','b','c']
list3=[100,200,300]
for item in zip(list1,list2,list3):
    print(item)



(1, 'a', 100)
(2, 'b', 200)
(3, 'c', 300)


In [126]:
list(zip(list1,list2))
# the location of zipped 
zip(list1,list2)
list(zip(list1,list2))


TypeError: 'list' object is not callable

In [127]:
for a,b,c in zip(list1,list2,list3):
    print(b)


a
b
c


In [128]:
#in keyWord
'x' in ['x','y','z']

True

In [129]:
1 in  ['x','y','z']

False

In [130]:
'a'in 'a world'

True

In [131]:
'mykey' in {'mykey':'value'}

True

In [132]:
d={'mykey':345}
345 in d.values()

True

In [133]:
#To get randomly your List 
from  random import shuffle
myList =[1,2,3,4,5,6,7]
shuffle(myList )
myList 

[5, 2, 3, 1, 6, 7, 4]

In [134]:
min (myList)

1

In [135]:
max(myList)

7

In [136]:
from random import randint


In [137]:
randint(0,100)

59

In [138]:
MyNummer= randint(0,10)

In [139]:
MyNummer

5

In [140]:
myString="hold On "
Vide_List=[]
for letter in myString :
    Vide_List.append(letter)   
Vide_List   


['h', 'o', 'l', 'd', ' ', 'O', 'n', ' ']

In [141]:
Vide_List=[letter for letter in myString]
Vide_List

['h', 'o', 'l', 'd', ' ', 'O', 'n', ' ']

In [142]:
#List Comprehension
result =[x for x in range(0,10) if x%2==0 ]
result

[0, 2, 4, 6, 8]

In [143]:
result_=[x if x%2==0 else 'Odd' for x in range(0,10)]
result_

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [152]:
MyList=[]
for x in [1,2,3]:
    for y in [1,2,3]:
        MyList.append(x*y)

In [153]:
AgainMyList=[(x*y)for x in [1,2,3] for y in [1,2,3]]

In [154]:
AgainMyList  

[1, 2, 3, 2, 4, 6, 3, 6, 9]

In [1]:
#map Function 
def time2(var):
    return var*2
aListToMap=[1,4,6,9,0]
resultMap=map(time2,aListToMap)
list(resultMap)


[2, 8, 12, 18, 0]

In [2]:
#lambda Expression 
#lambda Syntax
#lambda Argument:function 
t=lambda var:var*2
t(4)


8

In [3]:
from sqlalchemy import create_engine
engine=create_engine('sqlite:///:memory:')

In [4]:
 #Complete SQL engine 


In [6]:
#print(X_train)  

In [9]:
#print(y_train)

In [10]:
import numpy as np 
myList=[1,2,3]
arr=np.array(myList)
print(arr)    

[1 2 3]


In [11]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#The third argument c present the of number that we want int the intervall [a,b]
#np.linspace(a,b,c)
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#rand function give function between 0 and 1 while randn function give values from -∞ to the given number
np.random.rand(5)
np.random.rand(5,5)

array([[0.4458676 , 0.67119145, 0.79345947, 0.97812657, 0.35826839],
       [0.89438209, 0.95400479, 0.13205195, 0.96146998, 0.35594632],
       [0.35637836, 0.44606922, 0.47200465, 0.31354835, 0.87681681],
       [0.25109088, 0.08252368, 0.26668713, 0.82321191, 0.18847353],
       [0.23300291, 0.93236558, 0.69109755, 0.39998706, 0.47543597]])

In [22]:
np.random.randn(5)
np.random.randn(5,6)

array([[-1.45662364, -0.05320289, -0.48224689,  0.33107282, -0.64612876,
        -0.42063739],
       [-1.15908512, -0.46348556,  0.04787911, -0.14478061, -1.62408005,
         0.74389637],
       [-1.32264562,  0.24298274,  1.52159255,  1.54864565,  2.54096921,
        -1.06634558],
       [-0.68773695,  0.57896807, -0.11927966,  1.51361409,  1.01485649,
         0.01886237],
       [-0.33728563, -1.74668679, -0.62832022,  1.81549132,  1.72567044,
         1.79889465]])

In [23]:
np.random.randint(1,100)

6

In [24]:
#np.random.randint(a,b,c) the c argument is for the number of numbers that will be showed in the intervall [b,c]
np.random.randint(1,100,10)

array([55, 38, 40,  2, 26, 83,  7, 37, 88, 40])

In [25]:
import numpy as np
arr=np.arange(25)

In [26]:
 print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
 ranarr=np.random.randint(0,50,10)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
    ranarr.max()

46

In [30]:
#to know the Position of the maximum value 
ranarr.argmax()

3

In [31]:
#to know the Position of the minimum value 
ranarr.argmin()

6

In [32]:
#to know the type contained in your arrar 
arr.dtype

dtype('int32')

In [33]:
from numpy.random import randint
#randint(a,b,c)

In [34]:
arr=np.arange(0,11)
arr[8]

8

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [37]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
#Instead of Lists arrays have the Ability to broadCast that mean thae we Could change a range of value in the same Time like the Example Below
arr[0:5]=100
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr=arr[0:6]
slice_of_arr [:]=87

In [41]:
slice_of_arr

array([87, 87, 87, 87, 87, 87])

In [42]:
arr

array([87, 87, 87, 87, 87, 87,  6,  7,  8,  9, 10])

In [43]:
arr

array([87, 87, 87, 87, 87, 87,  6,  7,  8,  9, 10])

In [44]:
#python create view when we made a change an a array to avoid memory issue in Case of large array (the array after the change is a reference to the origin array that mean every change made in the second array will be doing also in  the origin array)

In [45]:
#to create an independent copy to the origin array we should use the function copy 
theOriginrArray=np.arange(15)
arr_copy=theOriginrArray.copy()

In [46]:
arr_copy[0:5]=98

In [47]:
arr_copy

array([98, 98, 98, 98, 98,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
theOriginrArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
arr2_d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
arr2_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#double Bracket format to get element from 2dArray 
arr2_d[0][0]

1

In [52]:
#Single Bracket format to get element from 2dArray 
arr2_d[1,2]

6

In [53]:
#it's recomended to use single Comma Bracket notation
arr2_d[:2,1:] 

array([[2, 3],
       [5, 6]])

In [54]:
arr2_d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2_d[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [56]:
#Conditional Selection
MyArray=np.arange(15)
boll_arr= MyArray>5
boll_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [57]:
MyArray=np.arange(15)
MyArray[boll_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
#to abbreviate line 71 and 72 statement we can do it in one line like Below
#
MyArray[MyArray>5]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
elements=np.arange(50).reshape(5,10)

In [60]:
elements[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [61]:
#Numpy Operation 
First_array=np.arange(17)
SecondArray=np.arange(17)
#Arrays Must be with the same shape
First_array+SecondArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [62]:
First_array-SecondArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
First_array*SecondArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256])

In [64]:
First_array-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84])

In [65]:
SecondArray*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500, 1600])

In [66]:
First_array+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116])

In [67]:
#0/0 it's Forbidden 
#Devision an array 
First_array/SecondArray


<ipython-input-67-9ed71d27a73a>:3: RuntimeWarning: invalid value encountered in true_divide
  First_array/SecondArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [68]:
1/First_array

<ipython-input-68-51329ae1452e>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/First_array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    ])

In [69]:
First_array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256], dtype=int32)

In [70]:
#universal Array functions
np.sqrt(First_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        ])

In [71]:
np.exp(First_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06])

In [72]:
np.max(First_array)

16

In [73]:
np.log(First_array)

<ipython-input-73-1043c7ba4cbb>:1: RuntimeWarning: divide by zero encountered in log
  np.log(First_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872])

In [74]:
#Numpy Exercices 
np.zeros(10)
np.ones(10)
np.ones(10)*5
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [75]:
Arr=[[0,1,2],[3,4,5],[6,7,8]]
np.array(Arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
randNumber=np.random.rand(1)
print(randNumber)

[0.02294546]


In [78]:
randMatrice=np.random.randn(5,5)
randMatrice

array([[ 1.24123456, -0.26594759,  0.0199182 ,  1.1872318 ,  2.29997088],
       [-1.46104884,  0.75056236,  2.75147361, -1.78106389,  0.45107974],
       [-1.58845393, -0.71692648, -1.12605883,  1.12287772,  0.11427592],
       [ 0.65592581,  0.62543248,  0.32695245, -0.45391343, -1.72141757],
       [ 1.47006019, -0.12945879,  1.17051877,  0.08322513, -0.18884198]])

In [79]:
np.linspace(0.01,1,100).round(2).reshape(10,10)
 

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [80]:
np.linspace(0,1,20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [81]:
import numpy as np
arrange=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]] 
mat=np.array(arrange)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
value20=mat[3,4]
value20

20

In [83]:
np.array([[2],[7],[11]])

array([[ 2],
       [ 7],
       [11]])

In [84]:
np.array(np.arange(21,26))

array([21, 22, 23, 24, 25])

In [85]:
np.array([[16,17, 18, 19, 20],[21, 22, 23, 24, 25]])
    

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
SumMat=mat[0]+mat[1]+mat[2]+mat[3]+mat[4]
SumMat
varSum=0
for i in SumMat:
    varSum+=i
varSum 

325

In [87]:
 np.std(mat)

7.211102550927978

In [88]:
 mat[:,0]+mat[:,1]+mat[:,2]+mat[:,3]+mat[:,4]

array([ 15,  40,  65,  90, 115])

In [89]:
#series(pandas Lib)
import numpy as np 
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr= np.array(my_data)
d={'a':10,'b':20,'c':30}

In [90]:
pd.Series(data=my_data)
#index Created by default

0    10
1    20
2    30
dtype: int64

In [91]:
pd.Series(data=my_data,index=labels)
#while label is in range of data the data we Can just use this statement Instead of the statement above 
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [92]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [93]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [94]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [95]:
#pd.Series hold a Variety of Object Types 
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [96]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [97]:
ser1=pd.Series([1,2,3,4],['USA','Germany','Japan','Vatican'])
ser1

USA        1
Germany    2
Japan      3
Vatican    4
dtype: int64

In [98]:
ser2=pd.Series([1,2,5,4],['Italy','Coury','Japan','Vatican'])
ser2

Italy      1
Coury      2
Japan      5
Vatican    4
dtype: int64

In [99]:
ser1['USA']

1

In [100]:
ser3=pd.Series(data=labels)
ser3[0]

'a'

In [101]:
ser1

USA        1
Germany    2
Japan      3
Vatican    4
dtype: int64

In [102]:
# the Values Doas havent a Same Key are returned as Nan Value
#Integers value are Converted to float type to  maitain all the information possible
ser1+ser2

Coury      NaN
Germany    NaN
Italy      NaN
Japan      8.0
USA        NaN
Vatican    8.0
dtype: float64

In [103]:
import pandas as pd
import numpy as np
from numpy.random import randn
#DataFrames
np.random.seed(101)
#seed function is to get the same random numbers
df=pd.DataFrame(randn(5,4),index=['A','B','C','D','E'],columns=['W','Y','X','Z'])
df

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [104]:
df['W']
df.W
#this two Statement are equalbut the first One is the most recomended

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [105]:
type(df['W'])

pandas.core.series.Series

In [106]:
type(df )

pandas.core.frame.DataFrame

In [107]:
#a DataFrame is a bunch of series that have the Same indew

In [108]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [109]:
#DataFrames offer the possibility to Create a new Column if dosen't exists or replace it if doas it exist 
df['new']=df['W']+df['Z']
df

W         Y         X         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [111]:
#drpping a Column 
#axis =0 reffer to rows while axis =1 reffer to Columns
#df.drop(' new ',axis=1)


In [112]:
df
#pandas dont drop the Column in the Origine DataFrame it keep it to save Dat from losing  

W         Y         X         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [116]:
#To defitively drop a Column weshould use inplace argument in drop function 
#df.drop('new',axis=1,inplace=True)
#print(df)

In [119]:
#df.drop('E',axis=0)
#by default drop function work on rows (axis=0)
df.drop('E')
    

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [120]:
df

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [121]:
df.drop('E',axis=0)

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [122]:
print("sdwxcgn")

sdwxcgn


In [123]:
df.shape

(5, 4)

In [124]:
df[['X','Y','Z']]

X         Y         Z
A  0.907969  0.628133  0.503826
B -0.848077 -0.319318  0.605965
C  0.528813  0.740122 -0.589001
D -0.933237 -0.758872  0.955057
E  2.605967  1.978757  0.683509

In [ ]:
#Selecting Rows in DataFrame

In [126]:
df.loc['A']
#return a Serie
#df.loc[ rowName]

W    2.706850
Y    0.628133
X    0.907969
Z    0.503826
Name: A, dtype: float64

In [132]:
df.iloc[4]
#return a Serie
#df.loc[ rowPosition]

W    0.190794
Y    1.978757
X    2.605967
Z    0.683509
Name: E, dtype: float64

In [133]:
#Selecting Subset of rows and Columns
df.loc['B','Y']

-0.31931804459303326

In [134]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.628133
B  0.651118 -0.319318

In [135]:
#Conditional Seclection
df>0

W      Y      X      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [139]:
bool=df>0
df[ bool]
#df[bool=df>0]

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [140]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [141]:
df[df['W']>0]

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [142]:
df[df['Z']<0]

W         Y         X         Z
C -2.018168  0.740122  0.528813 -0.589001

In [144]:
#resultDef =df[df['W']>0]
#resultDef['X']
df[df['W']>0]['X']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: X, dtype: float64

In [145]:
df[df['W']>0][['Y','X']]

Y         X
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [151]:
boolser=df['W']>0
result=df[boolser]
boolser
result[['Y','X']]
#MyCols=['Y','X']
#result(MyCols)

Y         X
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [153]:
df[(df['W']>0)&(df['Y']>1)]

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [154]:
df[(df['W']>0)|(df['Y']>1)]

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [155]:
df

W         Y         X         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [156]:
#to reset defitively your index you should as argument inplace =True ti the Function 
df.reset_index()
#the old index Became a column of the Dataframe.

index         W         Y         X         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [161]:
newind= 'CA NY WY OR CO'.split()

In [162]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [163]:
df['States']=newind

In [164]:
df

W         Y         X         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [166]:
df.set_index('States')

W         Y         X         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [8]:
import pandas as pd
#multiIndex&&indexHigherkey
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index) 

In [9]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [13]:
import numpy as np
df_=pd.DataFrame(np.random.randn(6,2),hier_index,['A','B'])

In [14]:
df_

A         B
G1 1 -2.172992  2.349532
   2  0.555526 -0.774032
   3 -1.127507  0.166331
G2 1  0.466480 -0.132727
   2  1.163748 -0.733217
   3  0.771663 -1.872113

In [15]:
#Call Data from MultiLevel Index
df_.loc['G1']

A         B
1 -2.172992  2.349532
2  0.555526 -0.774032
3 -1.127507  0.166331

In [17]:
df_.loc['G1'].loc[1]

A   -2.172992
B    2.349532
Name: 1, dtype: float64

In [18]:
df_.index.names

FrozenList([None, None])

In [19]:
df_.index.names=['Groups','Num']

In [20]:
df_

A         B
Groups Num                    
G1     1   -2.172992  2.349532
       2    0.555526 -0.774032
       3   -1.127507  0.166331
G2     1    0.466480 -0.132727
       2    1.163748 -0.733217
       3    0.771663 -1.872113

In [22]:
df_.loc['G2'].loc[2]['B']

-0.7332172210300991

In [24]:
#function is used to get cross-section from the Series/DataFrame.
#xs return a cross section of Multidomentional index
df_.xs

<bound method NDFrame.xs of                    A         B
Groups Num                    
G1     1   -2.172992  2.349532
       2    0.555526 -0.774032
       3   -1.127507  0.166331
G2     1    0.466480 -0.132727
       2    1.163748 -0.733217
       3    0.771663 -1.872113>

In [32]:
df_.xs(1,level='Num')

A         B
Groups                    
G1     -2.172992  2.349532
G2      0.466480 -0.132727

In [38]:
#Missing Value
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df__=pd.DataFrame(d)

In [39]:
df__

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [40]:
#dropna function each row contain A nan value
df__.dropna()

A    B  C
0  1.0  5.0  1

In [41]:
#to drop each Column contain A nan value
df__.dropna(axis=1)

C
0  1
1  2
2  3

In [49]:
#thresh argument represen the number of non nan value that should be in the row to keep it 
df__.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [50]:
#dropping Missing Value 
df__.fillna("Chaimaa")

A        B  C
0      1.0      5.0  1
1      2.0  Chaimaa  2
2  Chaimaa  Chaimaa  3

In [51]:
df__

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [54]:
df__['A'].fillna(value=df__['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [55]:
#Groupby with pandas
data={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,120,340,124,243,350]}


In [59]:
df___=pd.DataFrame(data)

In [62]:
byComp=df___.groupby('Company')

In [65]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [69]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [68]:
 byComp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [70]:
byComp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [71]:
byComp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [72]:
df___.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [73]:
df___.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [75]:
df___.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [76]:
df___.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [78]:
df___.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [80]:
df___.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [85]:
#Merging Joining and Concatenating
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']},index=[0,1,2,3])
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],'B':['B4','B5','B6','B7'],'C':['C4','C5','C6','C7'],'D':['D4','D5','D6','D7']},index=[4,5,6,7])
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],'B':['B8','B9','B10','B11'],'C':['C8','C9','C10','C11'],'D':['D8','D9','D10','D11']},index=[8,9,10,11])

In [86]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [87]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [88]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [89]:
#Concatenation 
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [90]:
#Concatenate by Column
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [91]:
#Merging
left=pd.DataFrame({'key':['K0','K1','K2','K3'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
right=pd.DataFrame({'key':['K0','K1','K2','K3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})

In [92]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [93]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [97]:
pd.merge(left,right,on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [98]:
pd.merge(left,right ,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [5]:
import pandas as pd
#Exemple
left_=pd.DataFrame({'key1':['K0','K0','K1','K2'],'key2':['K0','K1','K0','K1'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
right_=pd.DataFrame({'key1':['K0','K1','K1','K2'],'key2':['K0','K0','K0','K0'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})


In [8]:
pd.merge (left_,right_,on=['key1','key2'])
#right_

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [9]:
pd.merge (left_,right_, how='outer',on=['key1','key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [10]:
pd.merge (left_,right_, how='right',on=['key1','key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [11]:
pd.merge (left_,right_, how='left',on=['key1','key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [5]:
import pandas as pd
#Joining
left__=pd.DataFrame({'A':['A0','A1','A2'],'B':['B0','B1','B2']},index=['K0','K1','K2'])
right__=pd.DataFrame({'C':['C0','C2','C3'],'D':['D0','D2','D3']},index = ['K0','K2','K3'])

In [7]:
left__.join(right__)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [9]:
left__.join(right__,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3